---
name: wazuh-agent

releases:
- name: wazuh
  version: 3.0.0

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: wazuh-agent
  azs: [z1]
  instances: 1
  jobs:
  - name: wazuh-agent
    release: wazuh
    consumes:
      wazuh_properties: {from: wazuh_properties}
    provides:
      wazuh_properties: {as: wazuh_properties}
    properties:
      wazuh_server_ip: 10.0.15.15
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
