---
name: wazuh-server

releases:
- name: wazuh
  version: 3.0.0

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: wazuh-server
  azs: [z1]
  instances: 1
  jobs:
  - name: wazuh-server
    release: wazuh
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
  properties:
    sslmanager_key: ((sslmanager_ssl.private_key))
    sslmanager_cert: ((sslmanager_ssl.certificate))

variables:
- name: sslmanager_ca
  type: certificate
  options:
    is_ca: true
- name: sslmanager_ssl
  type: certificate
  options:
    ca: sslmanager_ca
