---
name: wazuh-server

releases:
- name: wazuh
  version: 3.10.2

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: wazuh-server
  azs: [z1]
  instances: 1
  jobs:
  - name: wazuh-server
    release: wazuh
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
  properties:
    cluster_key: "d683ecbf1f357cba8c86594dd0094a0c"
