meta:
  environment: ossec-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: ossec-server
    networks:
      - name: ossec1
        static_ips: (( static_ips 1 ))
  - name: ossec-agent
    networks:
      - name: ossec1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: ossec1
  type: manual
  subnets:
  - range: 10.244.221.0/24
    name: ossec1
    gateway: 10.244.221.1
    static:
      - 10.244.221.2 - 10.244.221.60

properties:
  forwarder:
    elasticsearch_hosts: (( grab jobs.ossec-server.networks[0].static_ips ))
  elasticsearch:
    cluster_name: ossec
    exec:
      environment:
        ES_HEAP_SIZE: 500000K
    master_hosts: (( grab jobs.ossec-server.networks[0].static_ips ))
  kibana:
    elasticsearch:
      host: (( grab jobs.ossec-server.networks[0].static_ips[0] ))
      port: 9200
  ossec:
    agent:
      server_ip: (( grab jobs.ossec-server.networks[0].static_ips[0] ))
    authd:
      password: RANDOM
      ssl_cert: (( file "ssl/server.crt" ))
      ssl_key: (( file "ssl/server.key" ))